#!/bin/bash
# -*- coding: utf-8 -*-
# Open Source Initiative OSI - The MIT License (MIT):Licensing
#
# The MIT License (MIT)
# Copyright (c) 2016 François-Xavier Bourlet (bombela+zerorpc@gmail.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

if [[ $# != 2 ]]; then
    echo "usage: $0 ZERORPC_SRC VERSION"
    exit -2
fi

ZERORPC_SRC=$1
VERSION=$2
ENV_DIR_P=".../$(basename $PWD)"
SRC_DIR="$(dirname "$(readlink -f "$0")")"

echo "$ENV_DIR_P - new env..."
if [[ "$VERSION" == "default" ]]; then
	NODE_BIN="node"
else
	NODE_BIN="node-$VERSION"
fi

if which "$NODE_BIN"; then
	NODE_BIN="$(which "$NODE_BIN")"
	echo "$ENV_DIR_P - using node: $NODE_BIN"
else
	echo "$ENV_DIR_P - cannot find: $NODE_BIN"
	exit -1
fi

echo "node: $(node --version)"
echo "npm: $(npm --version)"

echo "sym-linking test package..."
ln -sfv "$SRC_DIR/package.json" package.json

echo "sym-linking zerorpc (develop mode)..."
mkdir -p ./node_modules/zerorpc
for src_file in index.js lib LICENSE package.json README.md; do
	if [[ "$ZERORPC_SRC" == /* ]]; then
		ln -sfv "$ZERORPC_SRC/$src_file" "./node_modules/zerorpc/$src_file"
	else
		ln -sfv "../../$ZERORPC_SRC/$src_file" "./node_modules/zerorpc/$src_file"
	fi
done

echo "$ENV_DIR_P - Installing dependencies..."
npm install

echo "$ENV_DIR_P - Generating helper scripts..."

for helper in client server; do
    cat > "./$helper" <<EOF
#!/bin/sh
export NODE_PATH="$PWD/node_modules"
exec "$NODE_BIN" "$SRC_DIR/$helper.js" \$@
EOF
    chmod +x "./$helper"
done
