#!/bin/bash
# -*- coding: utf-8 -*-
# Open Source Initiative OSI - The MIT License (MIT):Licensing
#
# The MIT License (MIT)
# Copyright (c) 2016 François-Xavier Bourlet (bombela+zerorpc@gmail.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

if [[ $# != 2 ]]; then
    echo "usage: $0 ZERORPC_SRC VERSION"
    exit -2
fi

ZERORPC_SRC=$1
VERSION=$2
ENV_DIR_P=".../$(basename $PWD)"

if [ -x "./bin/python" ]; then
    echo "$ENV_DIR_P - reuse env"
else
    echo "$ENV_DIR_P - new env..."
    ARGS=
    if [[ "$VERSION" != "default" ]]; then
        ARGS="$ARGS -p python${VERSION}"
    fi
    virtualenv $ARGS "./"
fi

echo "$ENV_DIR_P - activate..."
source "./bin/activate"
echo "$ENV_DIR_P - activated $(which python)"

echo "Installing zerorpc (develop mode)..."
pip install -e "$ZERORPC_SRC"

echo "$ENV_DIR_P - Generating helper scripts..."
SRC_DIR="$(readlink -f $(dirname $0))"
PYTHON_BIN="$(readlink -f "./bin/python")"

for helper in client server; do
    cat > "./$helper" <<EOF
#!/bin/sh
exec "$PYTHON_BIN" "$SRC_DIR/$helper.py" \$@
EOF
    chmod +x "./$helper"
done

